#include <array>
#include <cmath>
#include <cstring>
#include <fstream>
#include <iostream>
#include <limits>
#include <random>

using namespace std;

// Graphene can be described by a 2D hexagonal lattice with
// a1 = a.x and a2 = a.sin(120).x + a.cos(120).y,
// with carbon atoms at position (0, 0) and  (2/3, 1/3).
// The lattice parameter a = 2.467 AA
// Thus simply related with the CC bond distance between the two atoms
// a = bond*sqrt(3)
//

double findMax(double** mat, int row, int a) {
  // Initializing max element as INT_MIN
  double maxElement = 0.0;

  // checking each element of matrix
  // if it is greater than maxElement,
  // update maxElement
  for (int i = 0; i < row; i++) {
    if (mat[i][a] > maxElement) {
      maxElement = mat[i][a];
    }
  }

  // finally return maxElement
  return maxElement;
}

double length(double* v1, double* v2) {
  //# v1(x1, y1, z1) and v2(x2, y2, z2) , length = sqrt((x2-x1)^2 + (y2-y1)^2 +
  //(z2-z1)^2)......
  double x1 = v1[0];
  double y1 = v1[1];
  double z1 = v1[2];

  double x2 = v2[0];
  double y2 = v2[1];
  double z2 = v2[2];

  double dis_sq = 0.0;
  dis_sq = ((x2 - x1) * (x2 - x1)) + ((y2 - y1) * (y2 - y1)) +
           ((z2 - z1) * (z2 - z1));

  double length_v1_v2 = 0.0;
  length_v1_v2 = sqrt(dis_sq);

  return (length_v1_v2);
};

double rand_num(int& a, int& b) {
  double R_num = 0.0;
  random_device
      rd;  // Will be used to obtain a seed for the random number engine
  mt19937 gen(rd());  // Standard mersenne_twister_engine seeded with rd()
  uniform_real_distribution<> dis(a, b);
  R_num = dis(gen);
  return (R_num);
};

int main() {
  int N;
  string fake;
  double percentage;
  ifstream inFile;
  inFile.open("input.in");
  inFile >> N;
  inFile >> fake;
  // cout<<fake<<"\n";

  inFile >> percentage;
  // cout<<percentage<<"\n";
  // int N = 256;
  // double percentage = 10.0;
  cout << N << "\n";
  cout << percentage << "\n";

  double mass1 = 48.0;
  double mass2 = 17.007;
  double mass3 = 15.99;

  int r = ceil(sqrt(N));
  int smallN = 1;
  double a = 2.86;
  double pi = 3.141592654;
  double** loc = new double*[N];
  double z = 0.0;
  double zero = 0.0;
  int two = 2;
  double check = 0;

  for (int i = 0; i < N; i++) {
    loc[i] = new double[4];
  }

  for (int j = 0; j < N; j++) {
    for (int i = 0; i < 4; i++) {
      loc[j][i] = 0.0;
    }
  }

  for (int j = 0; j < N; j++) {
    loc[j][0] = 1.0;
  }

  int counter = 2;
  int t = 0;
  int s = 0;
  int one = 1;
  int aa = 0;
  int bb = 0;

  ofstream outFile;
  ofstream outFile1, outFile2, outFile3, outFile4;
  outFile.open("Structure.xyz");
  outFile1.open("Structure.data");
  outFile2.open("bonds.txt");
  outFile3.open("angle.txt");
  outFile4.open("Structure.mol");

  outFile1 << "#LAMMPS graphene file generated by Rajat Code\n\n";

  for (int i = 0; i < int(sqrt(N)); i++) {
    for (int j = 1; j < r; j++) {
      if (t == 0) {
        loc[smallN][1] = loc[smallN - 1][1] + 2 * a;
        loc[smallN][2] = loc[smallN - 1][2];
        t = 1;
        smallN = smallN + 1;
      } else {
        loc[smallN][1] = loc[smallN - 1][1] + a;
        loc[smallN][2] = loc[smallN - 1][2];
        t = 0;
        smallN = smallN + 1;
      }
      if (smallN == N) {
        break;
      }
    }
    if (smallN == N) {
      break;
    }
    loc[smallN][2] = loc[smallN - 1][2] + a * sin(60 * pi / 180);
    if (s == 0) {
      loc[smallN][1] = a * cos(60 * pi / 180);
      s = 1;
      smallN = smallN + 1;
    } else {
      loc[smallN][1] = 0;
      s = 0;
      smallN = smallN + 1;
    }
  }

  // cout<<findMax(loc,N,1)<<"\n";
  // cout<<findMax(loc,N,2)<<"\n";

  int cc = N - 1;
  int r_id;
  bb = int((percentage * N / 100));

  int i = bb;

  cout << (bb) << "\n";
  while (i > 1) {
    // for hydroxyl group
    r_id = int(rand_num(aa, cc));
    if (loc[r_id][0] == 1.0) {
      loc[r_id][0] = 2.0;
      i = i - 1;
      // cout<<i<<"\n";
    }
  }

  i = bb;
  while (i > (0.5 * bb)) {
    // for epoxide group

    r_id = int(rand_num(aa, cc));
    if (loc[r_id][0] == 2.0) {
      loc[r_id][0] = 3.0;
      //      cout<<"r_id_O : "<<r_id<<"\n";
      i = i - 1;
    }
  }

  /*	for(int i = 0; i< bb; i++){
               // for hydroxyl group
                  r_id = int(rand_num(aa, cc));
                  cout<<"r_id_H : "<<r_id<<"\n";
                  loc[r_id-1][0] = 2.0;
                  // for epoxide group

                  r_id = int(rand_num(aa, cc));
                  cout<<"r_id_O : "<<r_id<<"\n";


                  loc[r_id-1][0] = 3.0;


          }

  */

  double* coords1 = new double[3];
  double* coords2 = new double[3];
  int numbond = 0;
  int three = 3;

  outFile2 << "\nBonds\n\n";

  for (int i = 0; i < N; i++) {
    for (int j = i; j < N; j++) {
      if (i != j) {
        coords1[0] = loc[i][1];
        coords1[1] = loc[i][2];
        coords1[2] = zero;

        coords2[0] = loc[j][1];
        coords2[1] = loc[j][2];
        coords2[2] = zero;
        if (length(coords1, coords2) < a + 0.1) {
          if (length(coords1, coords2) > a - 0.1) {
            numbond = numbond + 1;
            if (loc[i][0] == loc[j][0]) {
              outFile2 << numbond << "\t" << int(loc[i][0]) << "\t" << i + 1
                       << "\t" << j + 1 << "\n";
            } else {
              if ((loc[i][0] == 1.0 && loc[j][0] == 2) ||
                  (loc[i][0] == 2.0 && loc[j][0] == 1.0)) {
                outFile2 << numbond << "\t" << int(two) << "\t" << i + 1 << "\t"
                         << j + 1 << "\n";
              } else {
                outFile2 << numbond << "\t" << int(three) << "\t" << i + 1
                         << "\t" << j + 1 << "\n";
              }
            }
          }
        }
      }
    }
  }
  cout << "bond " << numbond << "\n";

  double numangle = 0;

  outFile3 << "\nAngles\n\n";

  for (int i = 0; i < N; i++) {
    for (int j = 0; j < N; j++) {
      if (i != j) {
        coords1[0] = loc[i][1];
        coords1[1] = loc[i][2];
        coords1[2] = zero;

        coords2[0] = loc[j][1];
        coords2[1] = loc[j][2];
        coords2[2] = zero;
        if (length(coords1, coords2) < a + 0.1) {
          if (length(coords1, coords2) > a - 0.1) {
            for (int k = 0; k < N; k++) {
              if (j != k && k != i) {
                coords1[0] = loc[j][1];
                coords1[1] = loc[j][2];
                coords1[2] = zero;

                coords2[0] = loc[k][1];
                coords2[1] = loc[k][2];
                coords2[2] = zero;
                check = 0.0;
                if (length(coords1, coords2) < a + 0.1) {
                  if (length(coords1, coords2) > a - 0.1) {
                    numangle = numangle + 1;
                    if (loc[i][0] == 1.0) check = check + 1;
                    if (loc[j][0] == 1.0) check = check + 1;
                    if (loc[k][0] == 1.0) check = check + 1;
                    if (check > 1) {
                      outFile3 << numangle << "\t" << one << "\t" << i + 1
                               << "\t" << j + 1 << "\t" << k + 1 << "\n";
                    } else {
                      check = 0;
                      if (loc[i][0] == 2.0) check = check + 1;
                      if (loc[j][0] == 2.0) check = check + 1;
                      if (loc[k][0] == 2.0) check = check + 1;
                      if (check > 1) {
                        outFile3 << numangle << "\t" << two << "\t" << i + 1
                                 << "\t" << j + 1 << "\t" << k + 1 << "\n";
                      } else {
                        outFile3 << numangle << "\t" << two << "\t" << i + 1
                                 << "\t" << j + 1 << "\t" << k + 1 << "\n";
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  cout << "angles " << numangle << "\n";

  outFile << N << "\n\n";
  outFile1 << N << "\t"
           << "atoms\n";

  outFile1 << numbond << " \tbonds\n";
  outFile1 << numangle << " \tangles\n";
  outFile1 << two + 1 << "\t atom types\n";
  outFile1 << two + 1 << "\t bond types\n";
  outFile1 << two + 1 << "\t angle types\n\n";

  outFile1 << zero << "\t" << (findMax(loc, N, 1) + 2.86) << " xlo xhi\n";
  outFile1 << zero << "\t" << (findMax(loc, N, 2) + 2.86) << " ylo yhi\n";
  outFile1 << zero << "\t" << double(7.5) << " zlo zhi\n\n";

  outFile1 << "Masses\n\n";
  outFile1 << one << "\t" << mass1 << "\n";
  outFile1 << one + 1 << "\t" << mass2 << "\n";
  outFile1 << one + 2 << "\t" << mass3 << "\n\n";

  /* for mol file */
  outFile4 << "Model for GO "
           << "\n\n";
  outFile4 << N << "\t"
           << "atoms\n";
  outFile4 << numbond << " \tbonds\n";
  outFile4 << numangle << " \tangles\n\n";
  outFile4 << "Coords\n\n";
  /// ,,,,,,,,,mol////////////////////////

  outFile1 << "Atoms\n\n";

  char atype[] = {'C', 'H', 'O'};
  int typeA;

  for (int i = 0; i < N; i++) {
    typeA = (int(loc[i][0]) - 1);

    outFile << atype[typeA] << "\t" << loc[i][1] << "\t" << loc[i][2] << "\t"
            << z << "\n";
    outFile1 << i + 1 << "\t" << i + 1 << "\t" << int(loc[i][0]) << "\t" << zero
             << "\t" << loc[i][1] << "\t" << loc[i][2] << "\t" << z << "\n";
    outFile4 << i + 1 << "\t" << loc[i][1] << "\t" << loc[i][2] << "\t" << z
             << "\n";
  }

  outFile4 << "\n";
  outFile4 << "Type"
           << "\n\n";

  for (int i = 0; i < N; i++) {
    outFile4 << i + 1 << "\t" << int(loc[i][0]) << "\n";
  }
  outFile4 << "\n";
  outFile4 << "Masses"
           << "\n\n";

  for (int i = 0; i < N; i++) {
    if (int(loc[i][0]) == 1) {
      outFile4 << i + 1 << "\t" << mass1 << "\n";
    } else if (int(loc[i][0]) == 2) {
      outFile4 << i + 1 << "\t" << mass2 << "\n";
    } else {
      outFile4 << i + 1 << "\t" << mass3 << "\n";
    }
  }

  outFile << "\n";

  outFile3 << "\n";

  outFile.close();
  outFile1.close();
  outFile2.close();
  outFile3.close();
  outFile4.close();
  system("cat Structure.data bonds.txt angle.txt > GO.data");
  system("cat Structure.mol bonds.txt angle.txt > GO.mol");
  system("cat Structure.xyz > GO.xyz");
  system("rm Structure.data Structure.xyz bonds.txt angle.txt  Structure.mol");

  return (0);
}
